### ISSUE TITLE
HttpServer Exercise - Help me understand the difference.

### ISSUE THREAD

**Issue by anupamkumar** [substack/stream-adventure#106]
How is my solution different from the Official solution ?

My solution:

```
var http = require('http');
var through = require('through');

var server = http.createServer(serverHandler);
var th = through(write,end);
server.listen(Number(process.argv[2]));

function serverHandler(req,res) {
	if(req.method === 'POST') 
		req.pipe(th).pipe(res);	
	else 
		res.end('Not permitted');	
}

function write(buf) {
	this.queue(buf.toString().toUpperCase());
}

function end() {
	this.queue(null);
}
```

The solution I have written does converts everything to upper case as required by the exercise, but when I try to verify my solution it fails. This is the output:

```
^C[anupam@localhost stream-adventure]$ stream-adventure verify httpserver1.js 
ACTUAL                             EXPECTED
------                             --------
"PLEASEKINDLY"                     "PLEASEKINDLY"                
"PLEASEKINDLY"                 !== "COMMUNICAKE"                 
"COMMUNICAKE"                  !== "WITH"                        
"WITH"                         !== "COMMUNICAKE"                 
"COMMUNICAKE"                  !== "WITH"                        
"WITH"                         !== "THE"                         
"THE"                              "THE"                         
"THE"                          !== "ORIGINAL"                    
"ORIGINAL"                         "ORIGINAL"                    
"ORIGINAL"                     !== "SINSE"                       
"SINSE"                            "SINSE"                       
"SINSE"                        !== "WE"                          
"WE"                               "WE"                          
"WE"                           !== "ARE"                         
"ARE"                              "ARE"                         
"ARE"                          !== "ONLY"                        
"ONLY"                             "ONLY"                        
"ONLY"                         !== "YEARNING"                    
"YEARNING"                         "YEARNING"                    
"YEARNING"                     !== "AS"                          
"AS"                               "AS"                          
"AS"                           !== "YET"                         
"YET"                              "YET"                         
"YET"                          !== "HOW"                         
"HOW"                              "HOW"                         
"HOW"                          !== "TO"                          
"TO"                           !== "BURGEON."                    
"BURGEON."                     !== "IT'S"                        
"IT'S"                         !== "TO"                          
"TO"                           !== "BURGEON."                    
"BURGEON."                     !== "IT'S"                        
"IT'S"                         !== "MEANT"                       
"MEANT"                            "MEANT"                       
"MEANT"                        !== "MILLIEMS"                    
"MILLIEMS"                         "MILLIEMS"                    
"MILLIEMS"                     !== "OF"                          
"OF"                               "OF"                          
"OF"                           !== "CENTIMENTS"                  
"CENTIMENTS"                       "CENTIMENTS"                  
"CENTIMENTS"                   !== ""                            
""                             !== null                          
# FAIL

Your solution didn't match the expected output.
Try again, or run `stream-adventure run program.js` to see your solution's output.
[anupam@localhost stream-adventure]$ 
```

Or this happens sometimes.

```
^C[anupam@localhost stream-adventure]$ stream-adventure verify httpserver1.js 
ACTUAL                             EXPECTED
------                             --------
"DEADLOST"                         "DEADLOST"                    
"OR"                           !== "MISLAID"                     
"DEADLOST"                     !== "OR"                          
"MISLAID"                      !== "ON"                          
"OR"                           !== "MISLAID"                     
"ON"                           !== "THEM"                        
"MISLAID"                      !== "ON"                          
"THEM"                         !== "BUT,"                        
"ON"                           !== "THEM"                        
"BUT,"                         !== "MASTER"                      
"THEM"                         !== "BUT,"                        
"MASTER"                       !== "OF"                          
"BUT,"                         !== "MASTER"                      
"OF"                           !== "SNAKES,"                     
"MASTER"                       !== "OF"                          
"SNAKES,"                      !== "WE"                          
"OF"                           !== "SNAKES,"                     
"WE"                           !== "CAN"                         
"SNAKES,"                      !== "WE"                          
"CAN"                          !== "SLOUGHCHANGE"                
"WE"                           !== "CAN"                         
"SLOUGHCHANGE"                 !== "IN"                          
"CAN"                          !== "SLOUGHCHANGE"                
"IN"                           !== "THE"                         
"SLOUGHCHANGE"                 !== "IN"                          
"THE"                          !== "NIP"                         
"IN"                           !== "OF"                          
"NIP"                          !== "THE"                         
"OF"                           !== "NIP"                         
"THE"                          !== "A"                           
"NIP"                          !== "OF"                          
"A"                            !== "NAPPLE"                      
"OF"                           !== "A"                           
"NAPPLE"                       !== "SOLONGAS"                    
"A"                            !== "NAPPLE"                      
"SOLONGAS"                     !== "WE"                          
"NAPPLE"                       !== "SOLONGAS"                    
ACTUAL SERVER Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at TCP.onread (net.js:558:19)
^C[anupam@localhost stream-adventure]$ 
```

The official solution works and gets verified correctly whereas my solution fails.

I feel that logically, both, my solution and official solution are doing exactly the same thing. Only difference is that I prefer to use named callback functions and while the official solution preferred anon callback function.

Please help me understand what I did wrong ?

**Comment by NickTomlin** [comment]
This is answered here: https://github.com/substack/stream-adventure/issues/77. 

Essentially, you are creating a single `through` stream and reusing it through multiple requests. You will need to create a new `through` stream on each request. You can still break out your write and end functions (all though the end function is unnecessary since that is the default), but you'll need to call through each time. The following adjusted code passes:

```javascipt
var http = require('http');
var through = require('through');

var server = http.createServer(serverHandler);
server.listen(Number(process.argv[2]));

function serverHandler(req,res) {
    if(req.method === 'POST')
        req.pipe(through(write,end)).pipe(res);
    else
        res.end('Not permitted');
}

function write(buf) {
    this.queue(buf.toString().toUpperCase());
}

function end() {
    this.queue(null);
}
```

Feel free to close this issue if that answers your question.
