### ISSUE TITLE
Doesn't work on windows 

### ISSUE THREAD

**Issue by dilignt** [substack/stream-adventure#38]
Installs fine, then trying to run it I get the following

```
$ stream-adventure

C:\Users\Mike\AppData\Roaming\npm\node_modules\stream-adventure\node_modules\terminal-menu\index.js:59
    process.stdin.setRawMode(true);
                  ^
TypeError: Object #<Socket> has no method 'setRawMode'
    at new Menu (C:\Users\Mike\AppData\Roaming\npm\node_modules\stream-adventure\node_modules\terminal-menu\index.js:59:19)
    at module.exports (C:\Users\Mike\AppData\Roaming\npm\node_modules\stream-adventure\node_modules\terminal-menu\index.js:7:12)
    at module.exports (C:\Users\Mike\AppData\Roaming\npm\node_modules\stream-adventure\bin\menu.js:9:16)
    at Object.<anonymous> (C:\Users\Mike\AppData\Roaming\npm\node_modules\stream-adventure\bin\cmd.js:125:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

**Comment by substack** [comment]
old version of node

**Comment by dilignt** [comment]
v 0.10.30
